homeassistant:
  name: Home
  latitude: 32.5316
  longitude: -95.3916
  elevation: 177
  unit_system: imperial
  time_zone: America/Chicago
  
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables cloud config
cloud:
  alexa:
    filter:
      include_domains:
        - switch
        - light
    entity_config:
      switch.guest_hallway_light_switch:
        display_categories: LIGHT
      switch.kitchen_light_switch:
        display_categories: LIGHT
      switch.laundry_room_light_switch:
        display_categories: LIGHT
      switch.garage_light_switch:
        display_categories: LIGHT
      switch.front_entryway_light_switch:
        display_categories: LIGHT
      switch.front_entryway_outside_light_switch:
        display_categories: LIGHT

# Enables web UI
http:
  api_password: !secret http_password
  base_url: https://home.johnny5th.com:443

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Z-Wave
zwave: 
  usb_path: /dev/ttyACM0
  network_key: "0x49, 0x43, 0x1D, 0xBD, 0x03, 0x6D, 0x9D, 0x8C, 0x39, 0x67, 0x16, 0x82, 0xA8, 0x67, 0xEE, 0x91"
  polling_interval: 10000

# iOS App
ios:

# HomeKit
homekit:
  auto_start: False
  filter:
    include_domains:
      - climate
      - device_tracker
      - light
      - switch
      - cover
      - lock

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

switch:
  - platform: command_line
    switches:
      aeotec_zstick_disco_light:
        friendly_name: 'Aeotec Z-Stick Disco Light'
        command_on: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/serial/by-id/usb-0658_0200-if00'
        command_off: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/serial/by-id/usb-0658_0200-if00'

